spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enhanced_url_shortener
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  redis:
    data:
      host: localhost
      port: 6379


application:
  security:
    jwt:
      secret-key: 1234567890  #https://seanwasere.com/generate-random-hex/
      expiration: 3600000
      refresh-token:
        expiration: 3600000

  key-gen:
    character-set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_
    base: 64
    key-size: 5
    batch-size: 10
    total-batches: 1

  redis-queue:
    threshold: 100

  scheduler:
    threshold-check: 300000

  domain: http://localhost:8080

  user:
    unregistered:
      email: user@unregistered.com
      expiration-days: 10


#spring.datasource.url=jdbc:mysql://localhost:3306/enhanced_url_shortener
#spring.datasource.username= 123
#spring.datasource.password= 123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.database-platform = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC